env:
  es6: true
parserOptions:
  sourceType: module

overrides:
  # basic rules
  - files:
      - "**/*.ts"
      - scripts/**/*.js
    extends:
      - eslint:recommended
      - prettier

  # Node.js environment
  - files:
      - src/node/**/*.ts
      - scripts/**/*.js
    env:
      es2017: true
      node: true
    parserOptions:
      ecmaVersion: 2019

  # browser environment
  - files:
      - src/browser/index.ts
    env:
      browser: true

  # pre-format JavaScript files
  - files:
      - "**/*.{js,mjs,cjs}"
    rules:
      lines-around-comment:
        - error
        - beforeBlockComment: true
          beforeLineComment: true
          allowBlockStart: true
          allowObjectStart: true
          allowArrayStart: true
          allowClassStart: true

  # rules for TypeScript
  - files:
      - "**/*.ts"
    extends:
      - plugin:@typescript-eslint/recommended
      - prettier/@typescript-eslint
    parser: "@typescript-eslint/parser"
    plugins:
      - "@typescript-eslint"
    rules:
      "@typescript-eslint/no-explicit-any": "off"
      "@typescript-eslint/no-empty-function": "off"

  # Source code for browsers
  - files:
      - src/browser/index.ts
    parserOptions:
      project: src/browser/tsconfig.json

  # Source code for Node.js
  - files:
      - src/node/**/*.ts
    parserOptions:
      project: src/node/tsconfig.json
